### ISSUE TITLE
install outter_space during bootstrap

### ISSUE THREAD

**Issue by kallaballa** [screeninvader/ScreenInvader#11]
Currently we are building images without a frontend. use npm to install outter_space.

**Comment by norpol** [comment]
or git submodules?

**Comment by ghost** [comment]
Ok, this may explain i got stuck at nginx...is there a short how-to or better wait until implementation? Due dependencies i cannot install npm inside SI-build by apt-get, also my understanding of outter_space readme is not good enough. Cheers.

**Comment by kallaballa** [comment]
they way im currently installing outta_space is cloning it outside the vm and then rsync it to /lounge/www

**Comment by ghost** [comment]
no 'npm install' or needed before rsync anyway?
thx

**Comment by kallaballa** [comment]
yes. you have to do npm instal in the base directory. after that run "npm  start &". that process is in charge of building bundle.js which is the "compiled" web app

**Comment by kallaballa** [comment]
outter_space is now installed during  bootstrap
