### ISSUE TITLE
makeimage.sh error

### ISSUE THREAD

**Issue by ghost** [screeninvader/ScreenInvader#13]
Hi,

i followed the guide to build an image on a Debian, 
at `./makeimage.sh -s 4000 -x ScreenInvader.dd`

i run into: `Make boot filesystem: failed`

Any idea?

Cheers:)

**Comment by kallaballa** [comment]
hi!

i've seen this error occasionally happen but i'm not sure what is causing  
it. just rerun it a second time and it should work. i'll try to track down  
the cause.

greets,
amir

**Comment by ghost** [comment]
Worked out, thanks.

**Comment by marcosnagele** [comment]
Hallo SI-Liste,

nachdem ein image-building dank Amir/Git geklappt hat, schreib jetzt 
hier, weils vielleicht etwas konfus wird für andere.

Hier mein vorgehen:

Nullen auf den Stick schreiben:
dd if=/dev/zero of=/dev/sdX

Image auf den Stick:
dd if=ScreenInvader.dd of=/dev/sdX bs=4M; sync

Ok, dann reboot von USB und Monitor pures schwarz.

Dann MBR auf den Stick geschrieben:
cat /usr/lib/EXTLINUX/mbr.bin > /dev/sdX

Wieder reboot, jetzt Fehlermeldung "No operating System"

Dann die erste Partition des Images am Stick per gparted gelöscht.

(Wozu eigentlich diese leere FAT16, boot-files sind auf der 2. ext4?
Noch ein Detail ohne Error auf der 2. partition, die /initrd.img wird 
mir als "broken" im Nautilus angezeit, obwohl die verlinkte Datei in 
/boot vorhanden ist)

Und siehe da, der SI schnurrt und booted, config geklappt, wieder 
reboot.

Jetzt rufe ich die lokale SI-URL auf und bekomme im Brwoser:
403 Forbidden
nginx/1.2.1

Soweit bin ich mal gekommen, für weitere Hilfe dankbar.

Zwei andere Fragen,
Hab ich den Git übrigens richtig verstanden, dass dieses Image nur für 
VM gedacht ist?
Und bringt zweite Frage, wird es fertifge Images zum Download geben?

Danke, vor allem dafür das Ding mal frisch zu machen, nachdem ich 
Kodi-Addons in meiner letzten WG laufen hatte, ist der SI für 
YT/Soundcloud superfein dagegen.

Liebe Grüße aus Linz
Max

**Comment by kallaballa** [comment]
fixed: b0e98343290c409db0e5e6e9bfae895b9d4a5cec
