### ISSUE TITLE
bootstrap.sh "Build janosh: failed"

### ISSUE THREAD

**Issue by ghost** [screeninvader/ScreenInvader#15]
Hi, after the game is before...

CPU & Mem total loaded, tried already allocate more via fstab, still same issue.

Here is the bootstrap.log at this point:

virtual memory exhausted: Cannot allocate memory
Makefile:82: recipe for target 'src/exception.o' failed
make: **\* [src/exception.o] Error 1
make: **\* Waiting for unfinished jobs....
src/json.cpp:72:1: fatal error: error writing to /tmp/cc7WGIG2.s: No space left on device
 }
 ^
compilation terminated.
src/lua_script.cpp:158:24: warning: 'janosh::Request janosh::lua::make_request(std::string, lua_State_, bool)' defined but not used [-Wunused-function]
 static janosh::Request make_request(string command, lua_State_ L, bool trigger = false) {
                        ^
The bug is not reproducible, so it is likely a hardware or OS problem.
Makefile:82: recipe for target 'src/json.o' failed
make: **\* [src/json.o] Error 1
mkdir -p ///lounge//bin
cp janosh ///lounge//bin
cp: cannot stat `janosh': No such file or directory
Makefile:91: recipe for target 'install' failed
make: **\* [install] Error 1

LG

**Comment by ghost** [comment]
Solved (on my 4 core intel), 

edited two files:
/third/build_janosh.sh
/third/build_kernel.sh

both changed  from `make -j8` to `make -j4`

**Comment by kallaballa** [comment]
i'll try to determine the number of cores automatically

**Comment by kallaballa** [comment]
done
