### ISSUE TITLE
Let site helpers return playlists/multiple items. 

### ISSUE THREAD

**Issue by phaer** [screeninvader/ScreenInvader#2]
At the moment helpes return a tuple of a media files url and title, this is just a quick reminder to handle arrays to support playlist or split videos like most of ORF TVThek.

**Comment by norpol** [comment]
FYI: mpv was running into the same issues (multiple/split) files and solved them with a shell script I think. Here is a somewhat related issue I've opened at [mpv](https://github.com/mpv-player/mpv/issues/1556).

**Comment by phaer** [comment]
Actually I think it's a  different issue: They seem to have had perfomance problems due to probing each file of a playlist. Ths issue is just a quick reminder that show.lua needs to handle lists sooner or later. We just use mplayer/mpv for playback anyway and don't handle that in ScreenInvader as far as i know
